[package]
name = "lsm6dsox"
version = "0.1.0"
authors = ["Tobias Bich <tobias.bich@iml.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stmems-driver-sys = { git = "ssh://git@gitlab.cc-asp.fraunhofer.de/awesome-halo-130/sw-universe/stmems-driver-sys.git", tag = "v0.1.0" }
